config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :urls, :only => [:create, :new, :show, :update, :destroy]
  resources :users, :only => [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'

  root 'sessions#welcome'

  match '*id' => 'urls#show', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :url
end

app/models/url.rb
class Url < ApplicationRecord
  validates :original_url, presence: true, url: true
  has_many :statistics, dependent: :delete_all

  def self.generate_url
    generated_slug = Digest::MD5.hexdigest "#{SecureRandom.uuid}#{DateTime.now}"

    generated_slug = generated_slug[0, 5]

    # If slug exists, generate a new slug.
    if Url.find_by slug: generated_slug
      generate_url
    else
      generated_slug
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :password, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/' unless logged_in?
  end

  def display_page_not_found
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  # Log in / Create new session
  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to '/login'
    end
  end

  def welcome
    @url = Url.new

    if logged_in?
      # Gives the user's shortened URLs
      @urls = Url.where(user_id: session[:user_id])
    end
  end

  # Log out
  def destroy
    if logged_in?
      session[:user_id] = nil
      redirect_to '/welcome'
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  skip_before_action :authorized, only: [:create, :show]

  def create
    original_url = params[:url][:original_url]
    original_url = normalize_url(original_url)
    @url = Url.new(original_url: original_url)
    @url.slug = Url.generate_url

    if logged_in?
      @url.user_id = current_user.id
    end

    if @url.save
      new_url = "#{request.protocol}#{request.host_with_port}/#{@url.slug}"

      # Flashes the new_url to the user.
      redirect_to '/', notice: new_url
    else
      # Display the same page, but this time it'll carry errors.
      redirect_to '/', alert: @url.errors.full_messages
    end
  end

  def show
    url = Url.find_by slug: params[:id]

    if url&.active && url.created_at + 7.days > DateTime.now
      statistic = Statistic.create(url_id: url.id, referer: request.referer, ip_address: request.remote_ip)
      redirect_to url.original_url
    else
      display_page_not_found
    end
  end

  # Disables a link
  def update
    @url = Url.find_by id: params[:id]

    if @url&.user_id == session[:user_id]
      @url.active = !@url.active
      @url.save
    end

    redirect_to '/'
  end

  # Permanently deletes a link
  def destroy
    @url = Url.find_by id: params[:id]

    if @url&.user_id == session[:user_id]
      @url.destroy
    end

    redirect_to '/'
  end

  private
    def url_params
      params[:url].permit(:original_url)
    end

    def normalize_url(original_url)
      if original_url.starts_with?('http://') || original_url.starts_with?('https://')
        original_url
      else
        "https://#{original_url}"
      end

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  # Register
  def create
    @user = User.create(user_params)

    session[:user_id] = @user.id

    redirect_to '/welcome'
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/new.html.erb
<!-- Displays a generated slug if there's one available. -->
<a href="<%= "#{flash.notice}" %>">
  <%= "#{flash.notice}" %>
</a>

<%= form_with scope: :url, url: urls_path, local: true do |form| %>

  <% if @url.errors.any? %>
    <ul style='list-style-type: none'>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    <ul>
  <% end %>

  <br>

  <%= form.text_field :original_url, placeholder: 'Link' %>

  <%= form.submit 'Generate Link' %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username %>

  <br>

  <%= form.label :password %>
  <%= form.text_field :password %>

  <%= form.submit %>

<% end %>